# Path to the log file
logfile = ""

# possible values: fatal, error, warn, info, debug, silly
loglevel = "info"

# possible values: "mainnet", "testnet" or "regtest"
network = "regtest"

# you will have to set this to "cln" or "lnd" if you have configuration values for both
node = "lnd"

# Whether to use Boltz Pro fee rates
pro = false

# The daemon can also operate without a lightning node
# standalone = false

# Custom referral ID to use when creating swaps
referralId = "my-referral"

mempoolApi = "https://mempool.space/api"
electrumUrl = "host.docker.internal:51001"

[LIGHTNING]
# Default fee limit in ppm for lightning payments. Can be overridden on a per-swap basis.
routingFeeLimitPpm = 2500

[BOLTZ]
# By default the daemon automatically connects to the official Boltz Backend for the network your node is on
# This value is used to overwrite that
url = "http://host.docker.internal:9001"

[DATABASE]
# Path to the SQLite database file
# path = "./test.db"

[LND]
# Host of the gRPC interface of LND
host = "host.docker.internal"

# Port of the gRPC interface of LND
port = 10003

# Path to the data directory of LND
# datadir = "~/.lnd"

# Path to a macaroon file of LND.
# The daemon needs to have permission to read various endpoints, generate addresses and pay invoices
# Not required if datadir is specified
macaroon = "~/.lnd/admin.macaroon"

# Path to the TLS certificate of LND
# Not required if datadir is specified
certificate = "~/.lnd/tls.cert"